#!/bin/sh
CURRDIR="$(dirname $0)";
COMMAND_EXISTS="${CURRDIR}/../utils/command-exists";
CLEAR_DATA_VOLUME="${CURRDIR}/../utils/clear-data-volume";
if [ "$(${COMMAND_EXISTS} docker)" != "1" ]; then
  printf -- 'docker is not installed.\n';
  exit 1;
fi;

CURRENT_TIMESTAMP="$(date +'%Y%M%d_%H%m%S')";
SVC_VERSION='4.0-alpine';
SVC_VERSION_UNDERSCORED="$(printf -- "${SVC_VERSION}" | sed -e 's|\.|_|g')";
CONTAINER_NAME="redis_${SVC_VERSION_UNDERSCORED}_${CURRENT_TIMESTAMP}";
DATA_VOLUME_PATH="${HOME}/.zscripts/data/${CONTAINER_NAME}";
SVC_PORT=6379;

mkdir -p "${DATA_VOLUME_PATH}";

printf -- ' ___ ___ ___ ___ ___ \n';
printf -- '| _ \ __|   \_ _/ __|\n';
printf -- '|   / _|| |) | |\__ \\\n';
printf -- '|_|_\___|___/___|___/\n';
printf -- '                     \n';

HOST_PORT="$1";
if [ "${HOST_PORT}" = "" ]; then HOST_PORT=${SVC_PORT}; fi;

docker run \
  --publish "${HOST_PORT}:${SVC_PORT}" \
  --name "${CONTAINER_NAME}" \
  --volume "${DATA_VOLUME_PATH}:/data" \
  redis:"${SVC_VERSION}" \
;

${CLEAR_DATA_VOLUME} "${DATA_VOLUME_PATH}";
