#!/bin/sh
set +e;
DATA_VOLUME_PATH="$1";
printf -- "Cleaning up the temporary data volume at ${DATA_VOLUME_PATH} requires root privileges: ";
sudo rm -rf "${DATA_VOLUME_PATH}";
REMOVAL_SUCCESS="$?";
if [ "${REMOVAL_SUCCESS}" = "0" ]; then
  printf -- '\nDONE. Exiting with code 0.\n';
else
  printf -- "\nERROR! Exiting with code ${REMOVAL_SUCCESS}.\n\n";
  printf -- "(\nyou may have to run the following to clear up manually:\nsudo rm -rf ${DATA_VOLUME_PATH}\n)\n";
fi;